name: Build docs

on:
  workflow_call:
    inputs:
      stellar-cli-ref:
        required: false
        default: 'main'
        type: string
        description: "Stellar-cli ref to build against. If empty, will use latest cli version"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout App Repo
        uses: actions/checkout@v4
        with:
          repository: "stellar/stellar-docs"
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'
          cache-dependency-path: '**/yarn.lock'

      - name: Install App Dependencies
        run: yarn --prefer-offline
        shell: bash

      - name: Copy Files From Stellar CLI
        run: yarn stellar-cli:build -- --cli-ref='${{ inputs.stellar-cli-ref }}'
        shell: bash

      - name: Build app
        run: yarn build
        shell: bash

      - name: Check if routes.txt file needs updating
        run: |
          if ! git diff --exit-code -- routes.txt; then
            echo 'The `routes.txt` file has changed. Please update the routes.txt file locally by running `yarn build` and push that change.'
            exit 1
          fi
