name: Crowdin Manual Upload and Download

on:
  workflow_dispatch:

jobs:
  trigger-upload:
    uses: ./.github/workflows/crowdin-upload-workflow.yml

  trigger-download:
    needs: [ trigger-upload ]
    uses: ./.github/workflows/crowdin-download-workflow.yml
