name: Crowdin Upload Action

on:
  workflow_call:
  workflow_dispatch:
  schedule:
    - cron: "5 0,2,4,6,8,10,12,14,16,18,20,22 * * *" # Runs every even hour at 5 minutes past

jobs:
  crowdin-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Docs Repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: "**/yarn.lock"

      - name: Install Dependencies
        run: yarn --prefer-offline --frozen-lockfile

      - name: Generate CLI Docs
        run: yarn stellar-cli:build

      - name: (temp) Fix CLI links
        run: yarn stellar-cli:fix-links
        shell: bash

      - name: Write Translations
        run: yarn write-translations

      - name: Crowdin push
        uses: crowdin/github-action@v2
        with:
          upload_sources: true
          upload_translations: false
          download_translations: false
          upload_sources_args: --delete-obsolete
        env:
          CROWDIN_PROJECT_ID: ${{ env.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
